config/routes.rb
Edopter::Application.routes.draw do
  get "/dummy", controller: "landing_page", action: "prepwork"

  root :to => "landing_page#show"

  get "/edopter", controller: "landing_page", action: "show", as: "home"
  get "/edopter/getstarted", controller: "landing_page", action: "sign_up", as: "start"

  get "edopter/signup", controller: "edopter", action: "signup", as: "sign_up"

  get "/edopter/signup/startup", controller: "edopter", action: "s_signup", as: "startup_signup"

  get "/edopter/signup/user", controller: "edopter", action: "u_signup", as: "user_signup"

  get "/session/new" => "sessions#log_in", as: "login_nav"
    
  get "/session/new/edopter" =>  "sessions#new_UsersSession", as: "user_login"
  
  get "/session/new/company" => "sessions#new_StartupsSession", as: "startup_login"

  post "/sessions" => "sessions#create", as: "sessions"

  delete "/sessions" => "sessions#destroy"

  get '/events/new', controller: 'events', action: 'new', as: 'new_event'
  post '/events', controller: 'events', action: 'create'

  get '/events', controller: 'events', action: 'index', as: 'events'
  get '/events/:id', controller: 'events', action: 'show', as: 'event'

  get '/events/:id/edit', controller: 'events', action: 'edit', as: 'edit_event'
  put '/events/:id', controller: 'events', action: 'update'

  delete '/events/:id', controller: 'events', action: 'destroy'

  get '/companies/new', controller: 'companies', action: 'new', as: 'new_company'
  post '/companies', controller: 'companies', action: 'create'

  get '/companies', controller: 'companies', action: 'index', as: 'companies'
  get '/companies/:id', controller: 'companies', action: 'show', as: 'company'

  get '/companies/:id/edit', controller: 'companies', action: 'edit', as: 'edit_company'
  put '/companies/:id', controller: 'companies', action: 'update'

  delete '/companies/:id', controller: 'companies', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/company.rb
class Company < ActiveRecord::Base


#has_many :events

end

app/models/event.rb
class Event < ActiveRecord::Base


#belongs_to :user

#belongs_to :company

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :events
has_many :companies

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find_by_id(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new
    @company.company_name = params[:company_name]
    @company.company_email = params[:company_email]
    @company.user_id = params[:user_id]
    @company.event_id = params[:event_id]
 

   if @company.save
      redirect_to company_url(@company), :notice => "Startup Account Creation Success!"
    else
      redirect_to new_user_url, :notice => "Try again."
    end
  end

  def edit
    @company = Company.find_by_id(params[:id])
  end

  def update
    @company = Company.find_by_id(params[:id])
    @company.company_name = params[:company_name]
    @company.company_email = params[:company_email]
    @company.user_id = params[:user_id]
    @company.event_id = params[:event_id]
    
    if @company.save
            redirect_to companies_url
          else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find_by_id(params[:id])
    @company.destroy
        redirect_to companies_url
      end
end

app/controllers/edopters_controller.rb
class EdoptersController < ApplicationController


	def show

	
	end


	def present
		
	end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_id(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new
    @event.user_id = params[:user_id]
    @event.company_id = params[:company_id]
    @event.event_name = params[:event_name]
    @event.event_date = params[:event_date]
    @event.event_description = params[:event_description]
    
    if @event.save
            redirect_to events_url
          else
      render 'new'
    end
  end

  def edit
    @event = Event.find_by_id(params[:id])
  end

  def update
    @event = Event.find_by_id(params[:id])
    @event.user_id = params[:user_id]
    @event.company_id = params[:company_id]
    @event.event_name = params[:event_name]
    @event.event_date = params[:event_date]
    @event.event_description = params[:event_description]
    
    if @event.save
            redirect_to events_url
          else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find_by_id(params[:id])
    @event.destroy
        redirect_to events_url
      end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController


	def show

	
	end

	def prepwork
		
	end


end

app/controllers/prepwork_controller.rb
class PrepworkController < ApplicationController


	def show
		
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end


	def create_Users_Session
		u = User.find_by_username
		if u.present? && u.password == params[:password]
      	session[:user_id] = u.id
      	redirect_to users, notice: "Signed in successfully."


     else
       redirect_to new_session_url, notice: "Nice try."
	end

end

	def create_Startup_Session
		s = Startup.find_by_company_name
		if s.present? && s.password == params[:password]
      	session[:company_id] = s.id 
      	redirect_to company_url, notice: "Signed in successfully."

     	else
       	redirect_to new_session_url, notice: "Nice try."
		end

	end

	def destroy
    reset_session
    redirect_to home_url, notice: "Signed out successfully."
  	end

 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
     end


  def create
    @user = User.new
    @user.username = params[:username]
    @user.password = params[:password]
    @user.interests = params[:interests]
    @user.about_me = params[:about_me]
    @user.name = params[:name]
    
      if @user.save
      redirect_to user_url(@user), :notice => "Edopter Account Creation Success!"
    else
      redirect_to new_user_url, :notice => "Username taken."
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.username = params[:username]
    @user.password = params[:password]
    @user.interests = params[:interests]
    @user.about_me = params[:about_me]
    @user.name = params[:name]
    
     if @user.save
      redirect_to users_url, :notice => "Updated successfully."
    else
      redirect_to edit_user_url(@user.id), :notice => "Try again."
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
        redirect_to users_url
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/prepwork_helper.rb
module PrepworkHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/companies/edit.html.erb
<h1>Editing Company #<%= @company.id %></h1>


<%= form_tag(company_url(@company), method: 'put') do %>

  <div>
    <%= label_tag :company_name %><br />
    <%= text_field_tag :company_name, @company.company_name %>
  </div>

  <div>
    <%= label_tag :company_email %><br />
    <%= text_field_tag :company_email, @company.company_email %>
  </div>

  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id, @company.user_id %>
  </div>

  <div>
    <%= label_tag :event_id %><br />
    <%= number_field_tag :event_id, @company.event_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Company" %>
  </div>

<% end %>

app/views/companies/index.html.erb
<h1>Startups</h1>

<p><%= link_to 'Begin Connecting Today!', new_company_url %></p>

<table>
  <thead>
    <tr>
      <th>Startup name</th>
      <th>Company email</th>
      <th>Events</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.company_name %></td>
      <td><%= company.company_email %></td>
      <td><%= company.events %></td>
  
      <td><%= link_to 'Show', company_url(company) %></td>
      <td><%= link_to 'Edit', edit_company_url(company) %></td>
      <td><%= link_to 'Destroy', company_url(company), method: 'delete', data: { confirm: "Do you really want to delete this company?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>Create Startup Profile</h1>


  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-responsive.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">
  </head>

<%= form_tag(companies_url, method: 'post') do %>


  <div>
    <%= label_tag :company_name %><br />
    <%= text_field_tag :company_name %>
  </div>

    </div>

    <div>
    <%= label_tag :company_email %><br />
    <%= text_field_tag :company_email %>
    </div>

    <div>
    <h6> Social URL </h6> <br />
    <%= text_field_tag :social_url %>
    </div>

    <div>
    <%= label_tag :industry %><br />
    <%= text_field_tag :bread_and_butter %>
    </div>

    <div>
    <%= label_tag :product %><br />
    <%= text_field_tag :product %>
  </div>
  
    <div>
    <%= submit_tag "Start Testing!" %>
    </div>
<% end %>

app/views/edopters/present.hmtl.erb
<h1> Howdy </h1>

app/views/edopters/u_signup.html.erb
<h1> </h1>

app/views/events/edit.html.erb
<h1>Editing Event #<%= @event.id %></h1>


<%= form_tag(event_url(@event), method: 'put') do %>

  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id, @event.user_id %>
  </div>

  <div>
    <%= label_tag :company_id %><br />
    <%= number_field_tag :company_id, @event.company_id %>
  </div>

  <div>
    <%= label_tag :event_name %><br />
    <%= text_field_tag :event_name, @event.event_name %>
  </div>

  <div>
    <%= label_tag :event_date %><br />
    <%= date_select_tag :event_date, @event.event_date %>
  </div>

  <div>
    <%= label_tag :event_description %><br />
    <%= text_area_tag :event_description, @event.event_description %>
  </div>

  
  <div>
    <%= submit_tag "Update Event" %>
  </div>

<% end %>

app/views/events/index.html.erb
<h1>Events</h1>

<p><%#= link_to 'Add a New Event', new_event_url %></p>

<h2></h2>


<table>
  <thead>
    <tr>
     <th>Startup/+</th>
      <th></th>
      <th>Event name</th>
      <th>Event date</th>
      <th>Event description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.user_id %></td>
      <td><%= event.company_id %></td>
      <td><%= event.event_name %></td>
      <td><%= event.event_date %></td>
      <td><%= event.event_description %></td>
  
      <td><%= link_to 'Show', event_url(event) %></td>
      <td><%= link_to 'Edit', edit_event_url(event) %></td>
      <td><%= link_to 'Destroy', event_url(event), method: 'delete', data: { confirm: "Do you really want to delete this event?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>


<%= form_tag(events_url, method: 'post') do %>


  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id %>
  </div>

    <div>
    <%= label_tag :company_id %><br />
    <%= number_field_tag :company_id %>
  </div>

    <div>
    <%= label_tag :event_name %><br />
    <%= text_field_tag :event_name %>
  </div>

    <div>
    <%= label_tag :event_date %><br />
    <%= date_select_tag :event_date %>
  </div>

    <div>
    <%= label_tag :event_description %><br />
    <%= text_area_tag :event_description %>
  </div>

  
  <div>
    <%= submit_tag "Create Event" %>
  </div>
<% end %>

app/views/landing_page/lp2.html.erb
<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Edopter</title>
		<link rel="stylesheet" type="text/css" href="css/bootstrap.c
		ss">
		<link rel="stylesheet" type="text/css" href="css/bootstrap-responsive.css">
		<link rel="stylesheet" type="text/css" href="css/main.css">
		<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<nav class="clearfix">
			<h1 class="">edopter</h1>
			
		</nav>
		<div class="row-fluid panel-back-1">
	  		<div class="span6 main_header">
	  			<h2>Connecting startups <br> and early adopters</h2>
	  		</div>
	  
		</div>
	<div class="panel-back-3 edopt">
	  		<div class="container">
	    		<div class="row-fluid">
			  		<div class="span7 spacing">
			  			<h2 class="sub_header_light">meet face-to-face</h2>
			  			<h3 class="color_header">connecting users and builders.</h3>
			  			<p class="color_switch">Where are these emerging companies? We bring the startups into the community so you can tinker and test the latest technolgoes before anyone else.</p>
			  			 <%= link_to "Let's Connect", users_url, class: "btn btn-large btn-block btn-primary site_button"  %>
		  			</div>
				</div>
		  	</div>
		  </div>
	  <div class="panel-back-3 edopt">
	  		<div class="container">
	    		<div class="row-fluid">
			  		<div class="span7 spacing">
			  			<h2 class="sub_header_light">meet face-to-face</h2>
			  			<h3 class="color_header">connecting users and builders.</h3>
			  			<p class="color_switch">Where are these emerging companies? We bring the startups into the community so you can tinker and test the latest technolgoes before anyone else.</p>
		  		<div class="span7">
		  				  			 
		  		<%= link_to "Let's Learn", events_url, class: "btn btn-large btn-block btn-primary site_button"  %>

	  			</div>
	  			
			</div>
	  	</div>
	  	<div class="container panel-back-4 edopt push_contain">
	    	<div class="row-fluid">
		  		<div class="span6 spacing">
		  			<h2 class="sub_header">Startups</h2>
		  			<h3>Accelerating the feedback loop.</h3>
		  			<p>Build. Measure. Learn. We have been encouraged to get out of the building. But where? And to whom? At Edopter, we help to advacne the feedback loop by bringing in users and potential users to play with your product and get a real-time analysis of what you have built. </p>
		  		</div>
		  		<br>
		  		<div class="span7">
		  			<%= link_to "Let's Test", events_url, class: "btn btn-large btn-block btn-primary site_button"  %>
		  			
		  			<%= link_to "Create an Event", new_event_url, class: "create_event"  %>
	
	  			</div>
	  			-
			</div>
	  	</div>
	  	<div>
	  		<h1>Our Team</h1>
	  		<ul id="team_layout">
	  			<li>
	  				<img src="/assets/kevin-lee.jpg">
	  				<h4>Kevin Lee</h4>`
	  				<p>User Experience</p>
	  				<a href="https://twitter.com/kleeee23">
	  					<img src="/assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=126517788&locale=en_US&trk=tyah">
	  					<img src="/assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="/assets/megan-mcsherry.jpg">
	  				<h4>Megan McSherry</h4>
	  				<p>Visual Design</p>
	  				<a href="https://twitter.com/meganmcsherry">
	  					<img src="/assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=218456114&authType=NAME_SEARCH&authToken=TnmE&locale=en_US&srchid=710529121370396269365&srchindex=1&srchtotal=6&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396269365%2CVSRPtargetId%3A218456114%2CVSRPcmpt%3Aprimary">
	  					<img src="/assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="/assets/mike-adeleke.jpg">
	  				<h4>Mike Adeleke</h4>
	  				<p>Front End</p>
	  				<a href="https://twitter.com/mikeadeleke">
	  					<img src="/assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=71052912&authType=NAME_SEARCH&authToken=rFRI&locale=en_US&srchid=710529121370396345557&srchindex=1&srchtotal=23&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396345557%2CVSRPtargetId%3A71052912%2CVSRPcmpt%3Aprimary">
	  					<img src="/assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="/assets/0d7aaaf.jpg">
	  				<h4>Wade Niday</h4>
	  				<p>User Experience &amp; Visual Design</p>
	  				<a href="https://twitter.com/NidayLikeFriday">
	  					<img src="/assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=24145713&authType=NAME_SEARCH&authToken=_opm&locale=en_US&srchid=710529121370396186681&srchindex=1&srchtotal=1&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396186681%2CVSRPtargetId%3A24145713%2CVSRPcmpt%3Aprimary">
	  					<img src="/assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="/assets/trooper.jpg">
	  				<h4>Yurij Bryndzia</h4>
	  				<p>Web Development</p>
	  				<a href="https://twitter.com/RookieInnovator">
	  					<img src="/assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=54078100&authType=NAME_SEARCH&authToken=E6zf&locale=en_US&srchid=710529121370396159165&srchindex=1&srchtotal=1&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396159165%2CVSRPtargetId%3A54078100%2CVSRPcmpt%3Aprimary">
	  					<img src="/assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  		</ul>
	  		<a href="mailto:mike@edopter.co">
	  			<button class="btn btn-large btn-block btn-primary site_button contact_button" type="button">Contact Us</button>
	  		</a>	
		</div>
	</body>
</html>

app/views/landing_page/show.html.erb
<html>	
	<head>
		<meta charset="UTF-8">
		<title>Edopter</title>
		<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="css/bootstrap-responsive.css">
		<link rel="stylesheet" type="text/css" href="css/main.css">
		<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<nav class="clearfix">
		<h1>edopter</h1>
	</nav>
		<div class="row-fluid panel-back-1 edopt">
	  		<div class="span8 offset1 main_header">
	  			<h2>Connecting startups <br> and early adopters</h2>
	  			  <%= link_to "let's go", start_url, class: "btn btn-large btn-block btn-primary site_button"   %>

		  				<p><%= link_to "join a meetup", events_url %></p>
	  		</div>
		</div>
		<div class="panel-back-2 edopt">
			<div class="container">
		    	<div class="row-fluid">
			  		<div class="span7 spacing">
			  			<h2 class="sub_header">see what's new</h2>
			  			<h3>early access to the 'new thing'.</h3>
			  			<p>Edopter - early adopters - like to try things first. Our mission is to connect you with emerging companies, becasue trying something out before it's cool...is cool.</p>
			  			<p><%= link_to "let's connect", users_url, class: "btn btn-large btn-block btn-primary site_button"  %></p>
		  				<p><%= link_to "join a meetup", events_url %></p>
		  			</div>
				</div>
		  	</div>
		  </div>
	  	<div class="panel-back-3 edopt">
	  		<div class="container">
	    		<div class="row-fluid">
			  		<div class="span7 spacing">
			  			<h2 class="sub_header_light">meet face-to-face</h2>
			  			<h3 class="color_header">connecting users and builders.</h3>
			  			<p class="color_switch">Where are these emerging companies? We bring the startups into the community so you can tinker and test the latest technolgoes before anyone else.</p>
			  			<p><%= link_to "see who's next", events_url, class: "btn btn-large btn-block btn-primary site_button"  %></p>
		  				<p><%= link_to "join a meetup", events_url %></p>
		  			</div>
	  			</div>
			</div>
	  	</div>
	  	<div class="panel-back-4 edopt">
	    	<div class="container">
		    	<div class="row-fluid">
			  		<div class="span7 spacing">
			  			<h2 class="sub_header">get helpful feedback</h2>
			  			<h3>accelerating focused feedback.</h3>
			  			<p>Build. Measure. Learn. We help advance the feedback loop by directing users to your product for a real-time analysis.</p>
			  			
			  			<p><%= link_to "let's test", new_company_url, class: "btn btn-large btn-block btn-primary site_button"  %></p>
		  				<p><%= link_to "join a meetup", events_url %></p>
		  			</div>
				</div>
			</div>
	  	</div>
	  	<div>
	  		<h2 class="sub_header_light contact_team">meet our team</h2>
	  		<ul id="team_layout">
	  			<li>
	  				<img src="./assets/kevin-lee.jpg">
	  				<h4>Kevin Lee</h4>
	  				<p>User Experience</p>
	  				<a href="https://twitter.com/kleeee23" target="_blank">
	  					<img src="./assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=126517788&locale=en_US&trk=tyah" target="_blank">
	  					<img src="./assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="./assets/megan-mcsherry.jpg">
	  				<h4>Megan McSherry</h4>
	  				<p>Visual Design</p>
	  				<a href="https://twitter.com/meganmcsherry" target="_blank">
	  					<img src="./assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=218456114&authType=NAME_SEARCH&authToken=TnmE&locale=en_US&srchid=710529121370396269365&srchindex=1&srchtotal=6&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396269365%2CVSRPtargetId%3A218456114%2CVSRPcmpt%3Aprimary" target="_blank">
	  					<img src="./assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="./assets/mike-adeleke.jpg">
	  				<h4>Mike Adeleke</h4>
	  				<p>Front End</p>
	  				<a href="https://twitter.com/mikeadeleke" target="_blank">
	  					<img src="./assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=71052912&authType=NAME_SEARCH&authToken=rFRI&locale=en_US&srchid=710529121370396345557&srchindex=1&srchtotal=23&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396345557%2CVSRPtargetId%3A71052912%2CVSRPcmpt%3Aprimary" target="_blank">
	  					<img src="./assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="./assets/0d7aaaf.jpg">
	  				<h4>Wade Niday</h4>
	  				<p>User Experience</p>
	  				<a href="https://twitter.com/NidayLikeFriday" target="_blank">
	  					<img src="./assets/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=24145713&authType=NAME_SEARCH&authToken=_opm&locale=en_US&srchid=710529121370396186681&srchindex=1&srchtotal=1&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396186681%2CVSRPtargetId%3A24145713%2CVSRPcmpt%3Aprimary" target="_blank">
	  					<img src="./assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  			<li>
	  				<img src="./assets/trooper.jpg">
	  				<h4>Yurij Bryndzia</h4>
	  				<p>Web Development</p>
	  				<a href="https://twitter.com/RookieInnovator" target="_blank">
	  					<img src="./img/TwitterHover.png">
	  				</a>
	  				<a href="http://www.linkedin.com/profile/view?id=54078100&authType=NAME_SEARCH&authToken=E6zf&locale=en_US&srchid=710529121370396159165&srchindex=1&srchtotal=1&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A710529121370396159165%2CVSRPtargetId%3A54078100%2CVSRPcmpt%3Aprimary" target="_blank">
	  					<img src="./assets/LinkedInHover.png">
	  				</a>
	  			</li>
	  		</ul>
	  		<a href="mailto:mike@edopter.co">
	  			<button class="btn btn-large btn-block btn-primary site_button contact_button" type="button">Contact Us</button>
	  		</a>
		</div>
	</body>
</html>

app/views/landing_page/sign_in.html.erb
<h1>Welcome!</h1>

<h3> <font color="black"> Are you an Edopter? </font></h3>
<%= link_to ("Become an Edopter!"), new_user_url, class: "btn btn-large"  %>

<div>
<h4><font color="black"> Or </font><h4>
</div>

<div>
<h3 ><font color="black"> Are you a Startup? </font></h3>

<%= link_to ("Start Testing!"), new_company_url, class: "btn btn-large"  %>
</div>

app/views/landing_page/sign_up.html.erb
<h1>Welcome!</h1>

<h3> <font color="black"> Are you an Edopter? </font></h3>
<%= link_to ("Become an Edopter!"), new_user_url, class: "btn btn-large"  %>

<div>
<h4><font color="black"> Or </font><h4>
</div>

<div>
<h3 ><font color="black"> Are you a Startup? </font></h3>

<%= link_to ("Start Testing!"), new_company_url, class: "btn btn-large"  %>
</div>

app/views/layouts/application.html.erb
<head>
  <title>Edopter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


	<nav>
		<ul class="nav nav-pills pull-right">
		<li class="active"><%= link_to "Home",home_url  %> </li>
			<li><% if session[:user_id].present? %>
       			<%= link_to "Sign Out", sessions_url, method: 'delete' %>
     			<% else %>
       			<li><%= link_to "Sign In", login_nav_url %> </li>
       			<li><%= link_to "Sign Up", start_url %> </li>
     			<% end %>
          
			<li><%= link_to "What's Next", events_url %> </li>
			<li class="disabled"><a href="#">30 Day!</a></li>
		</ul>
	</nav>	


    <% if session[:user_id].present? %>
      <p>Welcome back, <%= User.find(session[:user_id]).username %>!</p>
    <% end %>



<%= yield %>

</body>